title: Medicus Analytica
author: GitHub User
email: drkostadinkostadinov@gmail.com
description: > 
  Асистент катедра "Социална медицина и обществено здраве" МУ-Пловдив. 
  Лекар, магистър "Здравен мениджмънт и обществено здраве"

# social links
twitter_username: kostadinoffMD
github_username:  kostadinoff
linkedin_username: kostadinovmd

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
