title: Личен блог
author: GitHub User
email: drkostadinkostadinov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Асистент катедра "Социална медицина и обществено здраве" МУ-Пловдив. 
  Лекар, магистър "Здравен мениджмънт и обществено здраве"

# social links
twitter_username: kostadinoffMD
github_username:  kostadinoff

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
