title: Medicus Analytica
author: [GitHub User](_posts/2011-11-18-CV.md)
email: drkostadinkostadinov@gmail.com
description: > 
  Асистент катедра "Социална медицина и обществено здраве" МУ-Пловдив. 
  Лекар, магистър "Здравен мениджмънт и обществено здраве"

# social links
twitter_username: kostadinoffMD
github_username:  kostadinoff

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
